import re
from flask import current_app, url_for
from flask_mail import Mail, Message

def is_valid_email(email):
    # please don"t DOS, I don"t know regex, this is generated by AI
    # for who see this message, hello, nice to meet you!
    pattern = r"^[^@\s]+@(?:[^@\s]+\.)?ntu\.edu\.tw$"
    return re.match(pattern, email) is not None

def send_verification_email(email):
    mail = Mail(current_app)
    token = current_app.mail_verify_serializer.dumps(email, salt="email_verify_salt")
    msg = Message('Confirm Email', recipients=[email])
    link = url_for('auth.confirm_email', token=token, _external=True)
    msg.body = 'The verification link is {}'.format(link)
    mail.send(msg)
    return
